<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EshopGuard.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EshopGuard.Application.Tests" />
    <InternalsVisibleTo Include="EshopGuard.Api" />
    <InternalsVisibleTo Include="EshopGuard.Api.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EshopGuard.Data\EshopGuard.Data.csproj" />
    <ProjectReference Include="..\EshopGuard.Jobs\EshopGuard.Jobs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Email/Templates/**/*" />
    <EmbeddedResource Include="Protocols/Texts/*.yaml" />
  </ItemGroup>

</Project>
