using EshopGuard.Data.Configurations.Conventions;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Migrations.Operations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.Internal;
using Npgsql.EntityFrameworkCore.PostgreSQL.Migrations;

namespace EshopGuard.Data.Migrations;

/// <summary>
/// Adds <c>PARTITION BY …</c> to <c>CREATE TABLE</c> of the tables listed in <see cref="TableNames.PartitionedTables"/>.
/// EF Core cannot partition; columns, keys and foreign keys stay generated by EF, the partitions themselves are created
/// by explicit SQL in the migration (<c>Migrations/Sql/F1/02_partitions.sql</c>).
/// </summary>
#pragma warning disable EF1001 // Npgsql's options interface is internal API, required by the base constructor.
public sealed class EshopGuardMigrationsSqlGenerator(MigrationsSqlGeneratorDependencies dependencies, INpgsqlSingletonOptions npgsqlOptions)
    : NpgsqlMigrationsSqlGenerator(dependencies, npgsqlOptions)
#pragma warning restore EF1001
{
    /// <inheritdoc />
    protected override void Generate(CreateTableOperation operation, IModel? model, MigrationCommandListBuilder builder, bool terminate = true)
    {
        ArgumentNullException.ThrowIfNull(operation);
        ArgumentNullException.ThrowIfNull(builder);
        if (!TableNames.PartitionedTables.TryGetValue($"{operation.Schema}.{operation.Name}", out var partitionBy))
        {
            base.Generate(operation, model, builder, terminate);
            return;
        }

        base.Generate(operation, model, builder, terminate: false);
        builder.Append(" PARTITION BY ").Append(partitionBy);
        if (terminate)
        {
            builder.AppendLine(Dependencies.SqlGenerationHelper.StatementTerminator);
            EndStatement(builder);
        }
    }
}
