-- F1RowLevelSecurity Down: remove the policies and switch RLS off again.
DROP POLICY IF EXISTS tenant_isolation ON iam.memberships;
ALTER TABLE iam.memberships NO FORCE ROW LEVEL SECURITY;
ALTER TABLE iam.memberships DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON iam.invitations;
ALTER TABLE iam.invitations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE iam.invitations DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON iam.notification_settings;
ALTER TABLE iam.notification_settings NO FORCE ROW LEVEL SECURITY;
ALTER TABLE iam.notification_settings DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON iam.notifications;
ALTER TABLE iam.notifications NO FORCE ROW LEVEL SECURITY;
ALTER TABLE iam.notifications DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON shop.shops;
ALTER TABLE shop.shops NO FORCE ROW LEVEL SECURITY;
ALTER TABLE shop.shops DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON shop.shop_markets;
ALTER TABLE shop.shop_markets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE shop.shop_markets DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON shop.shop_languages;
ALTER TABLE shop.shop_languages NO FORCE ROW LEVEL SECURITY;
ALTER TABLE shop.shop_languages DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON shop.shop_verifications;
ALTER TABLE shop.shop_verifications NO FORCE ROW LEVEL SECURITY;
ALTER TABLE shop.shop_verifications DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON shop.connectors;
ALTER TABLE shop.connectors NO FORCE ROW LEVEL SECURITY;
ALTER TABLE shop.connectors DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON shop.connector_webhooks;
ALTER TABLE shop.connector_webhooks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE shop.connector_webhooks DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON shop.connector_events;
ALTER TABLE shop.connector_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE shop.connector_events DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON shop.feeds;
ALTER TABLE shop.feeds NO FORCE ROW LEVEL SECURITY;
ALTER TABLE shop.feeds DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON shop.page_profiles;
ALTER TABLE shop.page_profiles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE shop.page_profiles DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON shop.shop_facts;
ALTER TABLE shop.shop_facts NO FORCE ROW LEVEL SECURITY;
ALTER TABLE shop.shop_facts DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON content.pages;
ALTER TABLE content.pages NO FORCE ROW LEVEL SECURITY;
ALTER TABLE content.pages DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON content.page_versions;
ALTER TABLE content.page_versions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE content.page_versions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON checks.runs;
ALTER TABLE checks.runs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE checks.runs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON checks.run_events;
ALTER TABLE checks.run_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE checks.run_events DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON checks.jev_answers;
ALTER TABLE checks.jev_answers NO FORCE ROW LEVEL SECURITY;
ALTER TABLE checks.jev_answers DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON checks.sieve_answers;
ALTER TABLE checks.sieve_answers NO FORCE ROW LEVEL SECURITY;
ALTER TABLE checks.sieve_answers DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON checks.findings;
ALTER TABLE checks.findings NO FORCE ROW LEVEL SECURITY;
ALTER TABLE checks.findings DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON checks.finding_occurrences;
ALTER TABLE checks.finding_occurrences NO FORCE ROW LEVEL SECURITY;
ALTER TABLE checks.finding_occurrences DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON checks.questions;
ALTER TABLE checks.questions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE checks.questions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON checks.page_changes;
ALTER TABLE checks.page_changes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE checks.page_changes DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON fixes.fix_groups;
ALTER TABLE fixes.fix_groups NO FORCE ROW LEVEL SECURITY;
ALTER TABLE fixes.fix_groups DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON fixes.fix_proposals;
ALTER TABLE fixes.fix_proposals NO FORCE ROW LEVEL SECURITY;
ALTER TABLE fixes.fix_proposals DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON fixes.publications;
ALTER TABLE fixes.publications NO FORCE ROW LEVEL SECURITY;
ALTER TABLE fixes.publications DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON fixes.decision_memory;
ALTER TABLE fixes.decision_memory NO FORCE ROW LEVEL SECURITY;
ALTER TABLE fixes.decision_memory DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON fixes.evidence_items;
ALTER TABLE fixes.evidence_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE fixes.evidence_items DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON fixes.evidence_links;
ALTER TABLE fixes.evidence_links NO FORCE ROW LEVEL SECURITY;
ALTER TABLE fixes.evidence_links DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON fixes.protocols;
ALTER TABLE fixes.protocols NO FORCE ROW LEVEL SECURITY;
ALTER TABLE fixes.protocols DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON fixes.rewrite_cache;
ALTER TABLE fixes.rewrite_cache NO FORCE ROW LEVEL SECURITY;
ALTER TABLE fixes.rewrite_cache DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON billing.payment_methods;
ALTER TABLE billing.payment_methods NO FORCE ROW LEVEL SECURITY;
ALTER TABLE billing.payment_methods DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON billing.orders;
ALTER TABLE billing.orders NO FORCE ROW LEVEL SECURITY;
ALTER TABLE billing.orders DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON billing.subscriptions;
ALTER TABLE billing.subscriptions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE billing.subscriptions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON billing.subscription_changes;
ALTER TABLE billing.subscription_changes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE billing.subscription_changes DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON billing.payments;
ALTER TABLE billing.payments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE billing.payments DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON billing.invoices;
ALTER TABLE billing.invoices NO FORCE ROW LEVEL SECURITY;
ALTER TABLE billing.invoices DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON ops.schedules;
ALTER TABLE ops.schedules NO FORCE ROW LEVEL SECURITY;
ALTER TABLE ops.schedules DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON ops.outbox;
ALTER TABLE ops.outbox NO FORCE ROW LEVEL SECURITY;
ALTER TABLE ops.outbox DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON ops.audit_log;
ALTER TABLE ops.audit_log NO FORCE ROW LEVEL SECURITY;
ALTER TABLE ops.audit_log DISABLE ROW LEVEL SECURITY;
